name: Python Application test with Github Actions

on: [push]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.6
        uses: actions/setup-python@v3
        with:
          python-version: '3.6'
          
      - name: Install dependencies
        run: make install
      
      - name: Lint the PyLint
        run: make lint
        
      - name: Test with PyTest
        run: make test
